(* 
	This is an example EBNF file for basic arithmitic
*)
(*
	Lacking the patience for writing down 62 characters manually, the
	characters are defined in specials as regular expressions.
*)
letter = ? /[a-zA-Z]/ ?;
non_zero_digit = ? /[1-9]/ ?;
any_digit = "0" | non_zero_digit;
variable = { letter };
integer = non_zero_digit, [ { any_digit } ];
float = { any_digit }, ".", { any_digit };
numeric = variable | float | integer;
whitespace = ? /\s/ ?;
operator = "+" | "-" | "*" | "/" | "%" | "=";
operation = numeric, [ { whitespace } ], { operator }, [ { whitespace } ], numeric;
statement = { operation, [ { whitespace } ] , ";", [ { whitespace } ] };
